/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as VirtualIndexRouteImport } from "./routes/virtual/index"
import { Route as ProfileIndexRouteImport } from "./routes/profile/index"
import { Route as PlaygroundIndexRouteImport } from "./routes/playground/index"
import { Route as CreateIndexRouteImport } from "./routes/create/index"
import { Route as BluetoothIndexRouteImport } from "./routes/bluetooth/index"
import { Route as RoomRoomIdRouteImport } from "./routes/room/$roomId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualIndexRoute = VirtualIndexRouteImport.update({
  id: "/virtual/",
  path: "/virtual/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: "/playground/",
  path: "/playground/",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: "/create/",
  path: "/create/",
  getParentRoute: () => rootRouteImport,
} as any)
const BluetoothIndexRoute = BluetoothIndexRouteImport.update({
  id: "/bluetooth/",
  path: "/bluetooth/",
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: "/room/$roomId",
  path: "/room/$roomId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/room/$roomId": typeof RoomRoomIdRoute
  "/bluetooth": typeof BluetoothIndexRoute
  "/create": typeof CreateIndexRoute
  "/playground": typeof PlaygroundIndexRoute
  "/profile": typeof ProfileIndexRoute
  "/virtual": typeof VirtualIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/room/$roomId": typeof RoomRoomIdRoute
  "/bluetooth": typeof BluetoothIndexRoute
  "/create": typeof CreateIndexRoute
  "/playground": typeof PlaygroundIndexRoute
  "/profile": typeof ProfileIndexRoute
  "/virtual": typeof VirtualIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/room/$roomId": typeof RoomRoomIdRoute
  "/bluetooth/": typeof BluetoothIndexRoute
  "/create/": typeof CreateIndexRoute
  "/playground/": typeof PlaygroundIndexRoute
  "/profile/": typeof ProfileIndexRoute
  "/virtual/": typeof VirtualIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/room/$roomId"
    | "/bluetooth"
    | "/create"
    | "/playground"
    | "/profile"
    | "/virtual"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/room/$roomId"
    | "/bluetooth"
    | "/create"
    | "/playground"
    | "/profile"
    | "/virtual"
  id:
    | "__root__"
    | "/"
    | "/room/$roomId"
    | "/bluetooth/"
    | "/create/"
    | "/playground/"
    | "/profile/"
    | "/virtual/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  BluetoothIndexRoute: typeof BluetoothIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  VirtualIndexRoute: typeof VirtualIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/virtual/": {
      id: "/virtual/"
      path: "/virtual"
      fullPath: "/virtual"
      preLoaderRoute: typeof VirtualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/": {
      id: "/profile/"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/playground/": {
      id: "/playground/"
      path: "/playground"
      fullPath: "/playground"
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create/": {
      id: "/create/"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/bluetooth/": {
      id: "/bluetooth/"
      path: "/bluetooth"
      fullPath: "/bluetooth"
      preLoaderRoute: typeof BluetoothIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/room/$roomId": {
      id: "/room/$roomId"
      path: "/room/$roomId"
      fullPath: "/room/$roomId"
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  BluetoothIndexRoute: BluetoothIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  VirtualIndexRoute: VirtualIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
