/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ProfileIndexRouteImport } from "./routes/profile/index"
import { Route as CreateIndexRouteImport } from "./routes/create/index"
import { Route as RoomRoomIdRouteImport } from "./routes/room/$roomId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: "/create/",
  path: "/create/",
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: "/room/$roomId",
  path: "/room/$roomId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/room/$roomId": typeof RoomRoomIdRoute
  "/create": typeof CreateIndexRoute
  "/profile": typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/room/$roomId": typeof RoomRoomIdRoute
  "/create": typeof CreateIndexRoute
  "/profile": typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/room/$roomId": typeof RoomRoomIdRoute
  "/create/": typeof CreateIndexRoute
  "/profile/": typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/room/$roomId" | "/create" | "/profile"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/room/$roomId" | "/create" | "/profile"
  id: "__root__" | "/" | "/room/$roomId" | "/create/" | "/profile/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  CreateIndexRoute: typeof CreateIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/profile/": {
      id: "/profile/"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/create/": {
      id: "/create/"
      path: "/create"
      fullPath: "/create"
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/room/$roomId": {
      id: "/room/$roomId"
      path: "/room/$roomId"
      fullPath: "/room/$roomId"
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  CreateIndexRoute: CreateIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
